add_test_cases
openthread/silk pull request #2
Opened 2019-08-09 00:55 UTC by jenniexie

2019-08-09 04:54 UTC, qilinkang requested changes
. No cambrionix module under src.tools:
from src.tools import cambrionix

. Should we use a constant variable to define the timeout instead of 20 in the following line ? 20s maybe not enough for a device to join network and become a router.

return verify_within(check_device_role, 20, delay_time=5)

. We can use this constant for assert lines like this one:
self.assertTrue(r1_result, 'r1 cannot get into leader role after 180 seconds timeout')

2019-08-15 18:20 UTC, jenniexie commented
> . No cambrionix module under src.tools:
> from src.tools import cambrionix
> 
> . Should we use a constant variable to define the timeout instead of 20 in the following line ? 20s maybe not enough for a device to join network and become a router.
> 
> return verify_within(check_device_role, 20, delay_time=5)
> 
> . We can use this constant for assert lines like this one:
> self.assertTrue(r1_result, 'r1 cannot get into leader role after 180 seconds timeout')

I have fixed all comments

2019-08-15 18:24 UTC, qilinkang approved these changes
LGTM

2019-08-15 18:26 UTC, jwhui commented on src/tests/openthread/ot_test_leader_loss.py
> +from src.config import wpan_constants as wpan
License header?

2019-08-15 18:27 UTC, jwhui commented on src/tests/openthread/ot_test_partition_merge.py
> +from src.config import wpan_constants as wpan
License header?

2019-08-15 19:06 UTC, jenniexie commented on src/tests/openthread/ot_test_partition_merge.py
> +from src.config import wpan_constants as wpan
fixed

2019-08-15 19:06 UTC, jenniexie commented on src/tests/openthread/ot_test_leader_loss.py
> +from src.config import wpan_constants as wpan
fixed

2019-08-15 19:20 UTC, jwhui approved these changes

2019-08-15 19:21 UTC, merged